const mongoose = require('mongoose');

const listingSchema = new mongoose.Schema({
    id_mutation: { type: String },
    date_mutation: { type: Date, required: true },
    numero_disposition: { type: String },
    nature_mutation: { type: String },
    valeur_fonciere: { type: Number, required: true },
    adresse_numero: { type: String },
    adresse_suffixe: { type: String },
    adresse_nom_voie: { type: String },
    adresse_code_voie: { type: String },
    code_postal: { type: String },
    code_commune: { type: String },
    nom_commune: { type: String, required: true },
    code_departement: { type: Number, required: true },
    ancien_code_commune: { type: String },
    ancien_nom_commune: { type: String },
    id_parcelle: { type: String },
    ancien_id_parcelle: { type: String },
    numero_volume: { type: String },
    lot1_numero: { type: String },
    lot1_surface_carrez: { type: Number },
    lot2_numero: { type: String },
    lot2_surface_carrez: { type: Number },
    lot3_numero: { type: String },
    lot3_surface_carrez: { type: Number },
    lot4_numero: { type: String },
    lot4_surface_carrez: { type: Number },
    lot5_numero: { type: String },
    lot5_surface_carrez: { type: Number },
    nombre_lots: { type: Number },
    code_type_local: { type: String },
    type_local: { type: String , required:true},
    surface_reelle_bati: { type: Number, required: true },
    nombre_pieces_principales: { type: Number, required: true },
    code_nature_culture: { type: String },
    nature_culture: { type: String },
    code_nature_culture_speciale: { type: String },
    nature_culture_speciale: { type: String },
    surface_terrain: { type: Number },
    longitude: { type: Number },
    latitude: { type: Number }
});

module.exports = mongoose.model('Listing', listingSchema);
